/**
 * Los textos de las pantallas del usuario, en los tres idiomas.
 *
 * Clave/valor plano. La clave dice DÓNDE se lee («setup.wa.title»), no qué
 * dice: así el mismo texto en dos sitios se puede cambiar en uno solo sin
 * arrastrar el otro.
 *
 * Lo que NO se traduce y por eso no está aquí: los datos del CRM (nombres,
 * etapas, etiquetas) y las frases que se le mandan a Comando por WhatsApp,
 * que van en `wa.*` porque las lee el planificador y las lee también el
 * operador antes de enviarlas.
 */
import { register } from './i18n.js?v=1';

register({
  es: {
    /* ---------------------------------------------------------- comunes */
    'common.language': 'Idioma',
    'common.retry': 'Reintentar',
    'common.save': 'Guardar',
    'common.saving': 'Guardando…',
    'common.saved': 'Guardado.',
    'common.cancel': 'Cancelar',
    'common.continue': 'Continuar',
    'common.more': 'más',
    'common.loading': 'Cargando…',
    'common.none': 'Nada por aquí',
    'common.noData': 'Sin datos',
    'common.notLoaded': 'No se pudo cargar',
    'common.loadFailed': 'No pudimos cargar esta parte',
    'common.saveFailed': 'No se pudo guardar.',
    'common.failed': 'No se pudo',
    'common.dash': '—',
    'common.writeToComando': 'Escribir a Comando',
    'common.myAccount': 'Mi cuenta',
    'common.sections': 'Secciones',
    'common.mockBanner': 'Datos de ejemplo: nada de esto es real ni se guarda.',
    'common.exit': 'Salir',
    'common.askOnWhatsApp': 'Pedir por WhatsApp',
    'common.onWhatsApp': 'Por WhatsApp:',
    'common.send': 'enviar',
    'common.meanwhileAsk': 'Mientras tanto, pídelo por WhatsApp:',
    'common.comingSoon': '{what} se activa en tu cuenta muy pronto.',
    'common.thisPart': 'Esta parte',
    'common.sessionUnavailable': 'Sesión no disponible',
    'common.error': 'Error {status}',
  },
  en: {
    'common.language': 'Language',
    'common.retry': 'Try again',
    'common.save': 'Save',
    'common.saving': 'Saving…',
    'common.saved': 'Saved.',
    'common.cancel': 'Cancel',
    'common.continue': 'Continue',
    'common.more': 'more',
    'common.loading': 'Loading…',
    'common.none': 'Nothing here',
    'common.noData': 'No data',
    'common.notLoaded': 'Could not load',
    'common.loadFailed': 'We could not load this part',
    'common.saveFailed': 'Could not save.',
    'common.failed': 'Could not do it',
    'common.dash': '—',
    'common.writeToComando': 'Message Comando',
    'common.myAccount': 'My account',
    'common.sections': 'Sections',
    'common.mockBanner': 'Sample data: none of this is real or saved.',
    'common.exit': 'Exit',
    'common.askOnWhatsApp': 'Ask on WhatsApp',
    'common.onWhatsApp': 'On WhatsApp:',
    'common.send': 'send',
    'common.meanwhileAsk': 'In the meantime, ask for it on WhatsApp:',
    'common.comingSoon': '{what} switches on in your account very soon.',
    'common.thisPart': 'This part',
    'common.sessionUnavailable': 'Session unavailable',
    'common.error': 'Error {status}',
  },
  pt: {
    'common.language': 'Idioma',
    'common.retry': 'Tentar de novo',
    'common.save': 'Salvar',
    'common.saving': 'Salvando…',
    'common.saved': 'Salvo.',
    'common.cancel': 'Cancelar',
    'common.continue': 'Continuar',
    'common.more': 'mais',
    'common.loading': 'Carregando…',
    'common.none': 'Nada por aqui',
    'common.noData': 'Sem dados',
    'common.notLoaded': 'Não deu para carregar',
    'common.loadFailed': 'Não conseguimos carregar esta parte',
    'common.saveFailed': 'Não deu para salvar.',
    'common.failed': 'Não deu',
    'common.dash': '—',
    'common.writeToComando': 'Escrever para o Comando',
    'common.myAccount': 'Minha conta',
    'common.sections': 'Seções',
    'common.mockBanner': 'Dados de exemplo: nada disso é real nem fica salvo.',
    'common.exit': 'Sair',
    'common.askOnWhatsApp': 'Pedir pelo WhatsApp',
    'common.onWhatsApp': 'Pelo WhatsApp:',
    'common.send': 'enviar',
    'common.meanwhileAsk': 'Enquanto isso, peça pelo WhatsApp:',
    'common.comingSoon': '{what} entra na sua conta muito em breve.',
    'common.thisPart': 'Esta parte',
    'common.sessionUnavailable': 'Sessão indisponível',
    'common.error': 'Erro {status}',
  },
});

/* ================================================== vocabulario de la interfaz */
register({
  es: {
    'ui.dow': 'dom,lun,mar,mié,jue,vie,sáb',
    'ui.months': 'enero,febrero,marzo,abril,mayo,junio,julio,agosto,septiembre,octubre,noviembre,diciembre',
    'ui.dayLabel': '{dow} {day} de {month}',
    'ui.ago': 'hace {t}',
    'ui.in': 'en {t}',
    'ui.min': 'min',
    'ui.hour': 'h',
    'ui.day': 'd',
    'ui.million': 'M',
    'ui.thousand': 'k',
    'sev.critical': 'Crítico', 'sev.high': 'Alta', 'sev.warning': 'Media', 'sev.info': 'Baja', 'sev.ok': 'Bien',
    'signal.deal_inactive': 'Negocio inactivo', 'signal.close_date_approaching': 'Cierre próximo',
    'signal.close_date_overdue': 'Cierre vencido', 'signal.missing_next_step': 'Sin siguiente paso',
    'signal.overdue_task': 'Tarea vencida', 'signal.stage_stalled': 'Estancado en etapa',
    'signal.high_value_attention': 'Alto valor', 'signal.missing_owner': 'Sin dueño',
    'signal.missing_critical_data': 'Datos incompletos', 'signal.reconcile_age_hours': 'Sincronización',
    'signal.duplicate_records': 'Duplicados', 'signal.stale_records': 'Sin actividad',
    'signal.unassigned_records': 'Sin dueño', 'signal.open_tasks': 'Tareas abiertas', 'signal.signal_count': 'Señal',
    'phrase.deal_inactive': 'un negocio lleva {days} días sin que nadie lo toque',
    'phrase.close_date_approaching': 'un negocio cierra en menos de {days} días',
    'phrase.close_date_overdue': 'pasó la fecha de cierre y el negocio sigue abierto',
    'phrase.missing_next_step': 'un negocio se queda sin siguiente paso',
    'phrase.overdue_task': 'se te vence una tarea',
    'phrase.stage_stalled': 'un negocio lleva {days} días en la misma etapa',
    'phrase.high_value_attention': 'un negocio grande (desde {amount}) necesita atención',
    'phrase.missing_owner': 'entra un contacto o negocio sin dueño',
    'phrase.missing_critical_data': 'un negocio está sin monto, etapa o fecha de cierre',
    'cmd.TAG': 'Etiquetar', 'cmd.UNTAG': 'Quitar etiqueta', 'cmd.UPDATE_FIELD': 'Actualizar campo',
    'cmd.BROADCAST': 'Enviar plantilla', 'cmd.NOTE': 'Nota', 'cmd.ASSIGN': 'Asignar', 'cmd.MOVE_STAGE': 'Mover etapa',
    'cmd.CREATE_TASK': 'Crear tarea', 'cmd.CANCEL_TASK': 'Cancelar tarea', 'cmd.NOTIFY': 'Aviso',
    'cmd.GENERATE_REPORT': 'Reporte', 'cmd.CREATE_AUTOMATION_RULE': 'Regla por evento',
    'cmd.CREATE_AGENT_RULE': 'Aviso con cadencia', 'cmd.PAUSE_AUTOMATION': 'Pausar',
    'cmd.RESUME_AUTOMATION': 'Reanudar', 'cmd.UPDATE_MONEY': 'Montos', 'cmd.APPLY_DISCOUNT': 'Descuento',
    'cmd.CREATE_RECORD': 'Crear registro',
    'status.executed': 'Ejecutado', 'status.pending': 'Esperando CONFIRMAR', 'status.awaiting_approval': 'Esperando aprobación',
    'status.cancelled': 'Cancelado', 'status.failed': 'Falló · revertido', 'status.declined': 'No se pudo',
    'status.expired': 'Venció', 'status.approved': 'Aprobado', 'status.rejected': 'Rechazado',
    'status.active': 'Activa', 'status.paused': 'Pausada', 'status.sent': 'Enviado', 'status.deferred': 'Diferido',
    'status.suppressed': 'No enviado', 'status.open': 'Abierta', 'status.completed': 'Hecha',
    'status.snoozed': 'Pospuesta', 'status.verified': 'Verificado', 'status.soon': 'Próximamente',
  },
  en: {
    'ui.dow': 'Sun,Mon,Tue,Wed,Thu,Fri,Sat',
    'ui.months': 'January,February,March,April,May,June,July,August,September,October,November,December',
    'ui.dayLabel': '{dow} {month} {day}',
    'ui.ago': '{t} ago',
    'ui.in': 'in {t}',
    'ui.min': 'min',
    'ui.hour': 'h',
    'ui.day': 'd',
    'ui.million': 'M',
    'ui.thousand': 'k',
    'sev.critical': 'Critical', 'sev.high': 'High', 'sev.warning': 'Medium', 'sev.info': 'Low', 'sev.ok': 'Fine',
    'signal.deal_inactive': 'Deal inactive', 'signal.close_date_approaching': 'Closing soon',
    'signal.close_date_overdue': 'Close date passed', 'signal.missing_next_step': 'No next step',
    'signal.overdue_task': 'Overdue task', 'signal.stage_stalled': 'Stalled in stage',
    'signal.high_value_attention': 'High value', 'signal.missing_owner': 'No owner',
    'signal.missing_critical_data': 'Incomplete data', 'signal.reconcile_age_hours': 'Sync',
    'signal.duplicate_records': 'Duplicates', 'signal.stale_records': 'No activity',
    'signal.unassigned_records': 'No owner', 'signal.open_tasks': 'Open tasks', 'signal.signal_count': 'Signal',
    'phrase.deal_inactive': 'a deal goes {days} days without anyone touching it',
    'phrase.close_date_approaching': 'a deal closes in less than {days} days',
    'phrase.close_date_overdue': 'the close date passed and the deal is still open',
    'phrase.missing_next_step': 'a deal is left with no next step',
    'phrase.overdue_task': 'a task of yours falls due',
    'phrase.stage_stalled': 'a deal spends {days} days in the same stage',
    'phrase.high_value_attention': 'a big deal (from {amount}) needs attention',
    'phrase.missing_owner': 'a contact or deal comes in with no owner',
    'phrase.missing_critical_data': 'a deal has no amount, stage or close date',
    'cmd.TAG': 'Tag', 'cmd.UNTAG': 'Remove tag', 'cmd.UPDATE_FIELD': 'Update field',
    'cmd.BROADCAST': 'Send template', 'cmd.NOTE': 'Note', 'cmd.ASSIGN': 'Assign', 'cmd.MOVE_STAGE': 'Move stage',
    'cmd.CREATE_TASK': 'Create task', 'cmd.CANCEL_TASK': 'Cancel task', 'cmd.NOTIFY': 'Alert',
    'cmd.GENERATE_REPORT': 'Report', 'cmd.CREATE_AUTOMATION_RULE': 'Event rule',
    'cmd.CREATE_AGENT_RULE': 'Recurring alert', 'cmd.PAUSE_AUTOMATION': 'Pause',
    'cmd.RESUME_AUTOMATION': 'Resume', 'cmd.UPDATE_MONEY': 'Amounts', 'cmd.APPLY_DISCOUNT': 'Discount',
    'cmd.CREATE_RECORD': 'Create record',
    'status.executed': 'Ran', 'status.pending': 'Waiting for CONFIRM', 'status.awaiting_approval': 'Waiting for approval',
    'status.cancelled': 'Cancelled', 'status.failed': 'Failed · rolled back', 'status.declined': 'Could not',
    'status.expired': 'Expired', 'status.approved': 'Approved', 'status.rejected': 'Rejected',
    'status.active': 'Active', 'status.paused': 'Paused', 'status.sent': 'Sent', 'status.deferred': 'Deferred',
    'status.suppressed': 'Not sent', 'status.open': 'Open', 'status.completed': 'Done',
    'status.snoozed': 'Snoozed', 'status.verified': 'Verified', 'status.soon': 'Coming soon',
  },
  pt: {
    'ui.dow': 'dom,seg,ter,qua,qui,sex,sáb',
    'ui.months': 'janeiro,fevereiro,março,abril,maio,junho,julho,agosto,setembro,outubro,novembro,dezembro',
    'ui.dayLabel': '{dow} {day} de {month}',
    'ui.ago': 'há {t}',
    'ui.in': 'em {t}',
    'ui.min': 'min',
    'ui.hour': 'h',
    'ui.day': 'd',
    'ui.million': 'mi',
    'ui.thousand': 'mil',
    'sev.critical': 'Crítico', 'sev.high': 'Alta', 'sev.warning': 'Média', 'sev.info': 'Baixa', 'sev.ok': 'Bem',
    'signal.deal_inactive': 'Negócio parado', 'signal.close_date_approaching': 'Fecha em breve',
    'signal.close_date_overdue': 'Fechamento vencido', 'signal.missing_next_step': 'Sem próximo passo',
    'signal.overdue_task': 'Tarefa vencida', 'signal.stage_stalled': 'Parado na etapa',
    'signal.high_value_attention': 'Alto valor', 'signal.missing_owner': 'Sem dono',
    'signal.missing_critical_data': 'Dados incompletos', 'signal.reconcile_age_hours': 'Sincronização',
    'signal.duplicate_records': 'Duplicados', 'signal.stale_records': 'Sem atividade',
    'signal.unassigned_records': 'Sem dono', 'signal.open_tasks': 'Tarefas abertas', 'signal.signal_count': 'Sinal',
    'phrase.deal_inactive': 'um negócio fica {days} dias sem ninguém tocar',
    'phrase.close_date_approaching': 'um negócio fecha em menos de {days} dias',
    'phrase.close_date_overdue': 'passou a data de fechamento e o negócio segue aberto',
    'phrase.missing_next_step': 'um negócio fica sem próximo passo',
    'phrase.overdue_task': 'uma tarefa sua vence',
    'phrase.stage_stalled': 'um negócio fica {days} dias na mesma etapa',
    'phrase.high_value_attention': 'um negócio grande (a partir de {amount}) precisa de atenção',
    'phrase.missing_owner': 'entra um contato ou negócio sem dono',
    'phrase.missing_critical_data': 'um negócio está sem valor, etapa ou data de fechamento',
    'cmd.TAG': 'Etiquetar', 'cmd.UNTAG': 'Tirar etiqueta', 'cmd.UPDATE_FIELD': 'Atualizar campo',
    'cmd.BROADCAST': 'Enviar modelo', 'cmd.NOTE': 'Nota', 'cmd.ASSIGN': 'Atribuir', 'cmd.MOVE_STAGE': 'Mover etapa',
    'cmd.CREATE_TASK': 'Criar tarefa', 'cmd.CANCEL_TASK': 'Cancelar tarefa', 'cmd.NOTIFY': 'Aviso',
    'cmd.GENERATE_REPORT': 'Relatório', 'cmd.CREATE_AUTOMATION_RULE': 'Regra por evento',
    'cmd.CREATE_AGENT_RULE': 'Aviso com cadência', 'cmd.PAUSE_AUTOMATION': 'Pausar',
    'cmd.RESUME_AUTOMATION': 'Retomar', 'cmd.UPDATE_MONEY': 'Valores', 'cmd.APPLY_DISCOUNT': 'Desconto',
    'cmd.CREATE_RECORD': 'Criar registro',
    'status.executed': 'Executado', 'status.pending': 'Esperando CONFIRMAR', 'status.awaiting_approval': 'Esperando aprovação',
    'status.cancelled': 'Cancelado', 'status.failed': 'Falhou · revertido', 'status.declined': 'Não deu',
    'status.expired': 'Venceu', 'status.approved': 'Aprovado', 'status.rejected': 'Recusado',
    'status.active': 'Ativa', 'status.paused': 'Pausada', 'status.sent': 'Enviado', 'status.deferred': 'Adiado',
    'status.suppressed': 'Não enviado', 'status.open': 'Aberta', 'status.completed': 'Feita',
    'status.snoozed': 'Adiada', 'status.verified': 'Verificado', 'status.soon': 'Em breve',
  },
});

/* ============================================ filas y acciones compartidas */
register({
  es: {
    'row.taskDone': 'Hecha', 'row.move': 'Mover', 'row.cancel': 'Cancelar',
    'row.today': 'Hoy {time}', 'row.overdue': 'vencida {when}',
    'row.writeTo': 'Escribirle a {who}', 'row.customer': 'cliente',
    'row.seeDetail': 'Ver detalle', 'row.createTask': 'Crear tarea',
    'row.later': 'Luego', 'row.enough': 'Basta', 'row.why': 'Por qué',
    'row.asks': '{who} pide: {plan}', 'row.expires': '{reason} · vence {when}',
    'row.approve': 'Aprobar', 'row.reject': 'Rechazar', 'row.plan': 'Plan',
    'toast.remindTomorrow': 'Te lo recuerdo mañana.',
    'toast.dismissed': 'Listo, no te lo vuelvo a mostrar.',
    'toast.taskDone': 'Hecha.',
    'toast.closeOnWhatsApp': 'Ciérrala por WhatsApp: «hecha»',
    'toast.approved': 'Aprobado. Se ejecuta en unos segundos.',
    'toast.rejected': 'Rechazado.',
    'toast.paused': 'Pausado.', 'toast.resumed': 'Reanudado.',
    'prompt.rejectReason': '¿Por qué no? (le llega a quien lo pidió)',
    'sync.stale': '{provider} sin actualizar hace {age}',
    'sync.fresh': '{provider} al día · hace {age}',
    'hist.executed': 'Hecho', 'hist.pending': 'Espera tu CONFIRMAR', 'hist.awaiting_approval': 'Esperando al dueño',
    'hist.cancelled': 'Cancelado', 'hist.failed': 'No se pudo · revertido', 'hist.declined': 'No se pudo', 'hist.expired': 'Venció',
    'hist.confirm': 'Confirmar',
  },
  en: {
    'row.taskDone': 'Done', 'row.move': 'Move', 'row.cancel': 'Cancel',
    'row.today': 'Today {time}', 'row.overdue': 'overdue {when}',
    'row.writeTo': 'Message {who}', 'row.customer': 'customer',
    'row.seeDetail': 'See detail', 'row.createTask': 'Create task',
    'row.later': 'Later', 'row.enough': 'Stop', 'row.why': 'Why',
    'row.asks': '{who} asks: {plan}', 'row.expires': '{reason} · expires {when}',
    'row.approve': 'Approve', 'row.reject': 'Reject', 'row.plan': 'Plan',
    'toast.remindTomorrow': 'I will remind you tomorrow.',
    'toast.dismissed': 'Done, I will not show it again.',
    'toast.taskDone': 'Done.',
    'toast.closeOnWhatsApp': 'Close it on WhatsApp: “done”',
    'toast.approved': 'Approved. It runs in a few seconds.',
    'toast.rejected': 'Rejected.',
    'toast.paused': 'Paused.', 'toast.resumed': 'Resumed.',
    'prompt.rejectReason': 'Why not? (whoever asked will see it)',
    'sync.stale': '{provider} not updated for {age}',
    'sync.fresh': '{provider} up to date · {age} ago',
    'hist.executed': 'Done', 'hist.pending': 'Waiting for your CONFIRM', 'hist.awaiting_approval': 'Waiting for the owner',
    'hist.cancelled': 'Cancelled', 'hist.failed': 'Could not · rolled back', 'hist.declined': 'Could not', 'hist.expired': 'Expired',
    'hist.confirm': 'Confirm',
  },
  pt: {
    'row.taskDone': 'Feita', 'row.move': 'Mover', 'row.cancel': 'Cancelar',
    'row.today': 'Hoje {time}', 'row.overdue': 'vencida {when}',
    'row.writeTo': 'Escrever para {who}', 'row.customer': 'cliente',
    'row.seeDetail': 'Ver detalhe', 'row.createTask': 'Criar tarefa',
    'row.later': 'Depois', 'row.enough': 'Chega', 'row.why': 'Por quê',
    'row.asks': '{who} pede: {plan}', 'row.expires': '{reason} · vence {when}',
    'row.approve': 'Aprovar', 'row.reject': 'Recusar', 'row.plan': 'Plano',
    'toast.remindTomorrow': 'Te lembro amanhã.',
    'toast.dismissed': 'Pronto, não mostro de novo.',
    'toast.taskDone': 'Feita.',
    'toast.closeOnWhatsApp': 'Feche pelo WhatsApp: «feita»',
    'toast.approved': 'Aprovado. Executa em alguns segundos.',
    'toast.rejected': 'Recusado.',
    'toast.paused': 'Pausado.', 'toast.resumed': 'Retomado.',
    'prompt.rejectReason': 'Por que não? (chega para quem pediu)',
    'sync.stale': '{provider} sem atualizar há {age}',
    'sync.fresh': '{provider} em dia · há {age}',
    'hist.executed': 'Feito', 'hist.pending': 'Espera seu CONFIRMAR', 'hist.awaiting_approval': 'Esperando o dono',
    'hist.cancelled': 'Cancelado', 'hist.failed': 'Não deu · revertido', 'hist.declined': 'Não deu', 'hist.expired': 'Venceu',
    'hist.confirm': 'Confirmar',
  },
});

/* ====================================== las frases que se le mandan a Comando */
register({
  es: {
    'wa.confirm': 'CONFIRMAR', 'wa.cancel': 'cancela', 'wa.undo': 'deshacer',
    'wa.moveTask': 'mueve «{title}» para ', 'wa.cancelTask': 'cancela la tarea «{title}»',
    'wa.taskDone': 'hecha {title}',
    'wa.show': 'muéstrame {name}', 'wa.createTaskFor': 'créame una tarea para {name}',
    'wa.whyAlert': 'por qué me avisaste de {name}',
    'wa.whatMattersToday': 'qué merece mi atención hoy',
    'wa.whatToReview': 'qué debería revisar en mi CRM esta semana',
    'wa.lastThing': 'qué fue lo último que hice',
    'wa.newReminder': 'recuérdame mañana a las 10 llamar a ',
    'wa.thisWeek': 'qué tengo esta semana',
    'wa.nextStepOf': 'cuál es el siguiente paso de {name}',
    'wa.remindBefore': 'recuérdame «{title}» 2 horas antes',
    'wa.moneyInPlay': 'cuánta plata hay en juego ahorita',
    'wa.dealsByStage': 'dame los negocios por etapa con monto',
    'wa.dealsByStageAnd': 'dame los negocios por etapa pero partido por {field}',
    'wa.stalledDeals': 'qué negocios abiertos llevan más de 15 días sin que nadie los toque',
    'wa.stopAlert': 'no me avises más cuando {what}',
    'wa.pauseRule': 'pausa la regla «{name}»', 'wa.resumeRule': 'reanuda la regla «{name}»',
    'wa.changeRule': 'cámbiame la regla «{name}»: ',
    'wa.changeAlert': 'cámbiame el aviso «{name}» a ',
    'wa.pauseReport': 'pausa el reporte «{title}»',
    'wa.newAlert': 'avísame cuando ',
    'wa.myAlerts': 'qué avisos tengo activos',
    'wa.noMessagesToday': 'no me escribas hoy',
    'wa.quietHours': 'no me escribas después de las 9 de la noche',
    'wa.whichAutomations': 'qué automatizaciones me recomiendas',
    'wa.briefing': 'mándame el resumen {cadence} a las {time}',
    'wa.briefingDaily': 'cada mañana', 'wa.briefingWeekly': 'cada lunes', 'wa.briefingMonthly': 'cada mes',
    'wa.leadsPerCampaign': 'cuántos leads trajo cada campaña esta semana',
    'wa.connectAds': 'quiero conectar mis campañas de Facebook e Instagram',
    'wa.pauseCampaign': 'pausa la campaña «{name}»', 'wa.resumeCampaign': 'reanuda la campaña «{name}»',
    'wa.raiseBudget': 'súbele 20 % al presupuesto de «{name}»',
    'wa.campaignLeads': 'cuántos leads de «{name}» ya son negocios',
    'wa.applyRecommendation': 'aplica la recomendación de mi analista: {text}',
    'wa.askAnalyst': 'pregúntale a mi analista de marketing: ',
    'wa.pauseAutomation': 'pausa la automatización «{name}»', 'wa.resumeAutomation': 'reanuda la automatización «{name}»',
    'wa.newBudgetRule': 'si el costo por lead de una campaña pasa de 60 soles tres días seguidos, pausala y avísame',
    'wa.sendReport': 'mándame el reporte «{title}»',
    'wa.weeklyReport': 'mándame el reporte de campañas de esta semana',
    'wa.commandsLeft': 'cuántos comandos me quedan',
    'wa.changeRole': 'cambia el rol de {name} a ',
    'wa.whoUses': 'quiénes usan Comando en mi cuenta',
    'wa.forget': 'olvida que {what}',
    'wa.teachExample': 'para mí un negocio grande es desde 300 mil',
    'wa.teach': 'para mí ',
    'wa.weeklyAlert': 'avísame cada semana',
  },
  en: {
    'wa.confirm': 'CONFIRM', 'wa.cancel': 'cancel', 'wa.undo': 'undo',
    'wa.moveTask': 'move “{title}” to ', 'wa.cancelTask': 'cancel the task “{title}”',
    'wa.taskDone': 'done {title}',
    'wa.show': 'show me {name}', 'wa.createTaskFor': 'create me a task for {name}',
    'wa.whyAlert': 'why did you alert me about {name}',
    'wa.whatMattersToday': 'what deserves my attention today',
    'wa.whatToReview': 'what should I review in my CRM this week',
    'wa.lastThing': 'what was the last thing I did',
    'wa.newReminder': 'remind me tomorrow at 10 to call ',
    'wa.thisWeek': 'what do I have this week',
    'wa.nextStepOf': 'what is the next step for {name}',
    'wa.remindBefore': 'remind me about “{title}” 2 hours before',
    'wa.moneyInPlay': 'how much money is in play right now',
    'wa.dealsByStage': 'give me the deals by stage with amount',
    'wa.dealsByStageAnd': 'give me the deals by stage split by {field}',
    'wa.stalledDeals': 'which open deals have gone more than 15 days without anyone touching them',
    'wa.stopAlert': 'stop alerting me when {what}',
    'wa.pauseRule': 'pause the rule “{name}”', 'wa.resumeRule': 'resume the rule “{name}”',
    'wa.changeRule': 'change the rule “{name}”: ',
    'wa.changeAlert': 'change the alert “{name}” to ',
    'wa.pauseReport': 'pause the report “{title}”',
    'wa.newAlert': 'alert me when ',
    'wa.myAlerts': 'what alerts do I have active',
    'wa.noMessagesToday': 'do not message me today',
    'wa.quietHours': 'do not message me after 9 at night',
    'wa.whichAutomations': 'what automations do you recommend',
    'wa.briefing': 'send me the summary {cadence} at {time}',
    'wa.briefingDaily': 'every morning', 'wa.briefingWeekly': 'every Monday', 'wa.briefingMonthly': 'every month',
    'wa.leadsPerCampaign': 'how many leads did each campaign bring this week',
    'wa.connectAds': 'I want to connect my Facebook and Instagram campaigns',
    'wa.pauseCampaign': 'pause the campaign “{name}”', 'wa.resumeCampaign': 'resume the campaign “{name}”',
    'wa.raiseBudget': 'raise the budget of “{name}” by 20 %',
    'wa.campaignLeads': 'how many leads from “{name}” are deals already',
    'wa.applyRecommendation': 'apply my analyst recommendation: {text}',
    'wa.askAnalyst': 'ask my marketing analyst: ',
    'wa.pauseAutomation': 'pause the automation “{name}”', 'wa.resumeAutomation': 'resume the automation “{name}”',
    'wa.newBudgetRule': 'if the cost per lead of a campaign goes over 60 for three days in a row, pause it and tell me',
    'wa.sendReport': 'send me the report “{title}”',
    'wa.weeklyReport': 'send me this week campaign report',
    'wa.commandsLeft': 'how many commands do I have left',
    'wa.changeRole': 'change {name} role to ',
    'wa.whoUses': 'who uses Comando in my account',
    'wa.forget': 'forget that {what}',
    'wa.teachExample': 'for me a big deal starts at 300 thousand',
    'wa.teach': 'for me ',
    'wa.weeklyAlert': 'alert me every week',
  },
  pt: {
    'wa.confirm': 'CONFIRMAR', 'wa.cancel': 'cancela', 'wa.undo': 'desfazer',
    'wa.moveTask': 'move «{title}» para ', 'wa.cancelTask': 'cancela a tarefa «{title}»',
    'wa.taskDone': 'feita {title}',
    'wa.show': 'me mostra {name}', 'wa.createTaskFor': 'cria uma tarefa para {name}',
    'wa.whyAlert': 'por que você me avisou do {name}',
    'wa.whatMattersToday': 'o que merece minha atenção hoje',
    'wa.whatToReview': 'o que eu deveria revisar no meu CRM esta semana',
    'wa.lastThing': 'qual foi a última coisa que eu fiz',
    'wa.newReminder': 'me lembra amanhã às 10 de ligar para ',
    'wa.thisWeek': 'o que eu tenho esta semana',
    'wa.nextStepOf': 'qual é o próximo passo do {name}',
    'wa.remindBefore': 'me lembra de «{title}» 2 horas antes',
    'wa.moneyInPlay': 'quanto dinheiro está em jogo agora',
    'wa.dealsByStage': 'me dá os negócios por etapa com valor',
    'wa.dealsByStageAnd': 'me dá os negócios por etapa separado por {field}',
    'wa.stalledDeals': 'quais negócios abertos estão há mais de 15 dias sem ninguém tocar',
    'wa.stopAlert': 'não me avise mais quando {what}',
    'wa.pauseRule': 'pausa a regra «{name}»', 'wa.resumeRule': 'retoma a regra «{name}»',
    'wa.changeRule': 'muda a regra «{name}»: ',
    'wa.changeAlert': 'muda o aviso «{name}» para ',
    'wa.pauseReport': 'pausa o relatório «{title}»',
    'wa.newAlert': 'me avisa quando ',
    'wa.myAlerts': 'quais avisos eu tenho ativos',
    'wa.noMessagesToday': 'não me escreva hoje',
    'wa.quietHours': 'não me escreva depois das 9 da noite',
    'wa.whichAutomations': 'quais automações você recomenda',
    'wa.briefing': 'me manda o resumo {cadence} às {time}',
    'wa.briefingDaily': 'toda manhã', 'wa.briefingWeekly': 'toda segunda', 'wa.briefingMonthly': 'todo mês',
    'wa.leadsPerCampaign': 'quantos leads cada campanha trouxe esta semana',
    'wa.connectAds': 'quero conectar minhas campanhas do Facebook e Instagram',
    'wa.pauseCampaign': 'pausa a campanha «{name}»', 'wa.resumeCampaign': 'retoma a campanha «{name}»',
    'wa.raiseBudget': 'sobe 20 % do orçamento da «{name}»',
    'wa.campaignLeads': 'quantos leads da «{name}» já viraram negócio',
    'wa.applyRecommendation': 'aplica a recomendação do meu analista: {text}',
    'wa.askAnalyst': 'pergunta pro meu analista de marketing: ',
    'wa.pauseAutomation': 'pausa a automação «{name}»', 'wa.resumeAutomation': 'retoma a automação «{name}»',
    'wa.newBudgetRule': 'se o custo por lead de uma campanha passar de 60 três dias seguidos, pausa e me avisa',
    'wa.sendReport': 'me manda o relatório «{title}»',
    'wa.weeklyReport': 'me manda o relatório de campanhas desta semana',
    'wa.commandsLeft': 'quantos comandos me restam',
    'wa.changeRole': 'muda o papel do {name} para ',
    'wa.whoUses': 'quem usa o Comando na minha conta',
    'wa.forget': 'esquece que {what}',
    'wa.teachExample': 'para mim um negócio grande começa em 300 mil',
    'wa.teach': 'para mim ',
    'wa.weeklyAlert': 'me avisa toda semana',
  },
});

/* ======================================================= las seis secciones */
register({
  es: {
    'nav.hoy': 'Hoy', 'nav.agenda': 'Agenda', 'nav.crm': 'Mi CRM', 'nav.avisos': 'Avisos',
    'nav.marketing': 'Marketing', 'nav.cuenta': 'Cuenta',
    'sub.hoy': 'Qué hago ahora.',
    'sub.agenda': 'Tus recordatorios, visitas y cierres por día.',
    'sub.crm': 'Cuánta plata hay en juego y qué está viejo, vacío, repetido o sin dueño.',
    'sub.avisos': 'De qué te avisa Comando, cuándo te escribe y qué más puede vigilar.',
    'sub.marketing': 'Qué te traen tus anuncios de Facebook, Instagram y TikTok, y qué dice tu analista.',
    'sub.cuenta': 'Tu plan, tu CRM, tu equipo y lo que Comando sabe de ti.',
    /* Hoy */
    'hoy.greet.morning': 'Buenos días', 'hoy.greet.afternoon': 'Buenas tardes', 'hoy.greet.evening': 'Buenas noches',
    'hoy.operator': 'operador',
    'hoy.planWaiting': 'Un plan espera tu <b>CONFIRMAR</b>',
    'hoy.planExpires': '{plan} · vence {when}',
    'hoy.waitingOwner': 'Esperando que el dueño lo apruebe · {when}',
    'hoy.tray': 'Qué hago ahora', 'hoy.trayWhat': 'La bandeja',
    'hoy.nothingPending': 'Nada pendiente', 'hoy.silenceIsGood': 'El silencio es la buena noticia.',
    'hoy.dependOnYou_one': '{n} cosa que depende de ti. Toca una y sigue.',
    'hoy.dependOnYou_other': '{n} cosas que dependen de ti. Toca una y sigue.',
    'hoy.whenSomething': 'Cuando algo dependa de ti, aparece aquí.',
    'hoy.moneyInPlay': 'Plata en juego', 'hoy.openDeals': '{n} negocios abiertos', 'hoy.soonInAccount': 'Se activa pronto',
    'hoy.forToday': 'Para hoy', 'hoy.task_one': 'tarea', 'hoy.task_other': 'tareas',
    'hoy.overdue_one': '{n} vencida', 'hoy.overdue_other': '{n} vencidas', 'hoy.noneOverdue': 'Ninguna vencida',
    'hoy.waitingForYou': 'Te esperan', 'hoy.pending_one': 'pendiente', 'hoy.pending_other': 'pendientes',
    'hoy.deserve_one': '{n} merece tu atención', 'hoy.deserve_other': '{n} merecen tu atención',
    'hoy.nothingUrgent': 'Nada urgente',
    'hoy.hello': '{greet}, {name} 👋',
    'hoy.youHave_one': 'Tienes <b>{n} cosa</b> que depende de ti.',
    'hoy.youHave_other': 'Tienes <b>{n} cosas</b> que dependen de ti.',
    'hoy.nothingUrgentNow': 'Nada urgente por ahora.',
    'hoy.askByPhrase': 'Lo que necesites, pídelo por WhatsApp con una frase.',
    'hoy.review': 'Qué revisar en tu CRM', 'hoy.seeAll': 'Ver todo',
    'hoy.last': 'Lo último que pediste', 'hoy.neverWrote': 'Todavía no le has escrito a Comando.',
    'hoy.undoLast': 'Deshacer lo último',
    'hoy.connectCrm': 'Conecta tu CRM y Comando empieza a trabajar',
    'hoy.connectCrmSub': 'HubSpot, Salesforce o una hoja de Google, con el login del propio sistema. Sin CRM ya puedes escribirle por WhatsApp; con CRM ve tu embudo, te avisa y ejecuta.',
    'hoy.connectCrmBtn': 'Conectar mi CRM',
    /* Agenda */
    'agenda.allDay': 'Todo el día', 'agenda.expectedClose': 'cierre esperado', 'agenda.meeting': 'reunión',
    'agenda.nextStep': 'Siguiente paso', 'agenda.remindMe': 'Recordarme', 'agenda.newReminder': 'Nuevo recordatorio',
    'agenda.list': 'Lista', 'agenda.month': 'Mes',
    'agenda.pendingNote': 'Por ahora ves tus recordatorios. Los cierres esperados y las reuniones de tu CRM se suman pronto.',
    'agenda.meanwhile': 'Mientras tanto:',
    'agenda.overdue': 'Vencidas', 'agenda.today': 'Hoy', 'agenda.tomorrow': 'Mañana',
    'agenda.thisWeek': 'Esta semana', 'agenda.later': 'Más adelante',
    'agenda.nothing30': 'Nada en los próximos 30 días',
    'agenda.nothing30Sub': 'Pídele a Comando «recuérdame…» y aparece aquí.',
    'agenda.what': 'La agenda', 'agenda.done': 'Hechas · {n}',
    'agenda.calDow': 'lun,mar,mié,jue,vie,sáb,dom',
    'agenda.prevMonth': 'Mes anterior', 'agenda.nextMonth': 'Mes siguiente', 'agenda.todayBtn': 'Hoy',
    'agenda.legendTask': 'Recordatorio', 'agenda.legendMeeting': 'Visita o reunión', 'agenda.legendClose': 'Cierre esperado',
    'agenda.nothingThatDay': 'Nada ese día.',
    /* Mi CRM */
    'crm.whatMoney': 'La plata en juego',
    'crm.wonMonth': 'Ganado este mes', 'crm.lostMonth': 'Perdido este mes', 'crm.deals': '{n} negocios',
    'crm.byStage': 'Por etapa', 'crm.upToDate': 'Al día {when}', 'crm.askList': 'Pedir la lista',
    'crm.by': 'Por {field}',
    'crm.anyCut': 'Pide cualquier otro corte: «por distrito», «por tipo de inmueble».',
    'crm.askCross': 'Pedir el cruce',
    'crm.ownersNote': 'Tu CRM tiene <b>{crmOwners} dueño</b> cargado y en Comando son <b>{people} personas</b>: mientras no pongan el dueño en cada registro, nada va a distinguir quién lleva qué.',
    'crm.whatToReview': 'Qué revisar',
    'crm.neverDeletes': 'Comando detecta; nunca borra ni fusiona por su cuenta.',
    'crm.seeList': 'Ver la lista', 'crm.alertWeekly': 'Avisarme cada semana',
    'crm.howInCrm': 'Cómo lo sacas en tu CRM:',
    'crm.of': 'de {of} ({pct} %)',
    'crm.contacts': 'Contactos',
    /* Avisos */
    'avisos.turnOff': 'Apagar', 'avisos.pause': 'Pausar', 'avisos.resume': 'Reanudar', 'avisos.change': 'Cambiar',
    'avisos.changeDayHour': 'Cambiar día u hora',
    'avisos.times_one': '1 vez esta semana', 'avisos.times_other': '{n} veces esta semana',
    'avisos.lastValue': 'la última vez: <b>{value}</b>', 'avisos.alertedYou': 'te avisó {when}',
    'avisos.sendsYou': 'Te manda «{title}»', 'avisos.byWhatsApp': 'por WhatsApp',
    'avisos.always': 'Siempre', 'avisos.whenSomething': 'Cuando pasa algo', 'avisos.everySoOften': 'Cada cierto tiempo',
    'avisos.title': 'Comando te avisa cuando…',
    'avisos.watchesNothing': 'Todavía no vigila nada', 'avisos.watchesNothingSub': 'Dile «avísame cuando…» o «cada lunes…».',
    'avisos.notListed': 'Algunos avisos todavía no se listan aquí.', 'avisos.askHim': 'Pregúntale:',
    'avisos.replyWords': 'Cada aviso acepta respuesta por WhatsApp: VER, OK, LUEGO, BASTA, POR QUÉ.',
    'avisos.newAlert': 'Nuevo aviso',
    'avisos.schedule': 'Horario', 'avisos.dontWriteFrom': 'No me escribas desde', 'avisos.until': 'hasta',
    'avisos.dailyLimit': 'Máximo de avisos por día',
    'avisos.proactive': 'Comando puede escribirme sin que le pregunte',
    'avisos.briefing': 'Resumen de la mañana', 'avisos.every': 'Cada',
    'avisos.daily': 'día (lunes a sábado)', 'avisos.weekly': 'lunes', 'avisos.monthly': 'mes, el primer día hábil',
    'avisos.at': 'A las', 'avisos.neverEmpty': 'Nunca llega vacío: si no hay nada, no te escribe.',
    'avisos.dayOff': '¿Un día sin avisos?', 'avisos.scheduleWhat': 'El horario',
    'avisos.whenWrites': 'Cuándo te escribe',
    'avisos.outsideHours': 'Lo que cae fuera del horario llega a primera hora, marcado como «de anoche».',
    'avisos.ideas': 'Ideas para activar con una frase', 'avisos.ideasWhat': 'Las ideas',
    'avisos.activate': 'Activar', 'avisos.allActivated': 'Ya activaste todas las ideas.',
    'avisos.ideasSub': 'Comando la convierte en aviso, te muestra la vista previa y espera tu CONFIRMAR.',
    'avisos.prefsSaved': 'Listo. Aplica desde el próximo aviso.', 'avisos.done': 'Listo.',
    /* Marketing */
    'mk.vsPrev': '{sign}{pct} % vs. el periodo anterior',
    'mk.connected': 'conectada', 'mk.needsAuth': 'falta autorizar', 'mk.soon': 'pronto',
    'mk.connectAnother': 'Conectar otra',
    'mk.spend': 'Inversión · {period}', 'mk.leadsIn': 'Leads que entraron',
    'mk.cpl': 'Costo por lead', 'mk.cpa': 'Costo por venta',
    'mk.sale_one': '{n} venta', 'mk.sale_other': '{n} ventas',
    'mk.campaigns': 'Campañas',
    'mk.spent': 'gastó <b>{spend}</b>', 'mk.leadsAt': '<b>{leads}</b> leads a {cpl}',
    'mk.won_one': '{n} ganado', 'mk.won_other': '{n} ganados',
    'mk.raiseBudget': 'Subir presupuesto', 'mk.seeLeads': 'Ver sus leads',
    'mk.campaignsSub': 'Pausar o cambiar presupuesto pasa por vista previa y CONFIRMAR, como todo.',
    'mk.analyst': 'Tu analista',
    'mk.reviewsWeekly': 'Revisa tus campañas cada semana · próxima: {when}',
    'mk.recommends': 'Te recomienda',
    'mk.impact': '{date} · impacto {impact}', 'mk.apply': 'Aplicar',
    'mk.nothingPending': 'Nada pendiente. Lo anterior ya está aplicado.',
    'mk.underReview': 'En revisión', 'mk.alreadyAsked': 'Lo que ya le preguntaste',
    'mk.askHim': 'Preguntarle',
    'mk.funnel': 'Del anuncio a la venta',
    'mk.automations': 'Lo que se hace solo',
    'mk.timesMonth_one': '1 vez este mes', 'mk.timesMonth_other': '{n} veces este mes',
    'mk.new': 'Nueva', 'mk.reports': 'Reportes', 'mk.toWhatsApp': 'Al WhatsApp',
    'mk.reportsSub': 'Semanal los lunes, mensual el primer día hábil.', 'mk.askNow': 'Pedir ahora',
    'mk.what': 'Marketing',
    'mk.extra': 'Conecta tu cuenta de anuncios y Comando empieza a seguir cada lead hasta la venta.',
    'mk.askOnWhatsApp': 'Preguntar por WhatsApp',
    'mk.connectSoon': 'La conexión de cuentas de anuncios se activa pronto. Escríbenos: hola@comando.pro',
    'mk.nextReview': 'Lo verás en la próxima revisión.',
    /* Cuenta */
    'cuenta.plan': 'Plan {name} · US$ {price}/{interval}',
    'cuenta.month': 'mes', 'cuenta.year': 'año',
    'cuenta.ofCommands': 'de {n} comandos este mes',
    'cuenta.over80': 'Pasaste el 80 %.', 'cuenta.renews': 'Se renueva el {date}',
    'cuenta.usageWhat': 'El consumo', 'cuenta.yourPlan': 'Tu plan: {plan}.',
    'cuenta.yourAccount': 'Tu cuenta', 'cuenta.edit': 'Editar',
    'cuenta.notLinked': 'Sin vincular', 'cuenta.youWriteTo': 'le escribes a Comando al {number}',
    'cuenta.changeNumber': 'Cambiar número', 'cuenta.changePlan': 'Cambiar de plan',
    'cuenta.yourCrm': 'Tu CRM',
    'cuenta.mirror': '{contacts} contactos · {deals} negocios a tu alcance',
    'cuenta.crmSub': 'Se conecta con el login del propio CRM, sin copiar claves. Solo el CRM activo se consulta cuando hablas con Comando.',
    'cuenta.adAccounts': 'Tus cuentas de anuncios',
    'cuenta.noAdAccounts': 'Sin cuentas conectadas',
    'cuenta.noAdAccountsSub': 'Meta (Facebook e Instagram) y TikTok Ads, con el mismo login seguro.',
    'cuenta.forMarketing': 'Para la sección Marketing.', 'cuenta.connect': 'Conectar', 'cuenta.authorize': 'Autorizar',
    'cuenta.seeCampaigns': 'Ver campañas',
    'cuenta.team': 'Tu equipo',
    'role.owner': 'Dueño', 'role.admin': 'Admin', 'role.supervisor': 'Supervisor', 'role.agent': 'Vendedor', 'role.analyst': 'Analista',
    'cuenta.waUnverified': 'WhatsApp sin verificar', 'cuenta.changeRole': 'Cambiar rol',
    'cuenta.ownersNote': 'Tu CRM tiene <b>{crmOwners} dueño</b> cargado y aquí son <b>{people}</b>. Hasta que pongan el dueño en cada registro, «mis negocios» no distingue personas.',
    'cuenta.teamWhat': 'Tu equipo',
    'cuenta.teamExtra': 'Cada persona se registra con su propio WhatsApp en comando.pro/app.',
    'cuenta.teamSub': 'Cada persona tiene su propio WhatsApp y su propio cupo.', 'cuenta.invite': 'Invitar',
    'cuenta.knows': 'Lo que Comando sabe de ti', 'cuenta.forget': 'Olvidar',
    'cuenta.knowsNothing': 'Todavía nada. Dile «para mí un negocio grande es desde 300 mil».',
    'cuenta.knowsSub': 'Solo aprende lo que le dices explícitamente; nunca en silencio.',
    'cuenta.teachHim': 'Enseñarle algo',
    'cuenta.privacy': 'Privacidad y salida',
    'cuenta.privacy1': 'Tus datos se quedan en tu CRM; Comando guarda solo los campos que activaste.',
    'cuenta.privacy2': 'Lo que le escribes se conserva 90 días para poder diagnosticar fallos; nadie lo lee sin tu pedido.',
    'cuenta.privacy3': 'Nunca le escribe a tus clientes desde tu número: prepara el mensaje y lo mandas tú.',
    'cuenta.privacyPolicy': 'Política de privacidad', 'cuenta.deleteAccount': 'Pedir el borrado de mi cuenta',
    'cuenta.signOut': 'Cerrar sesión',
    'cuenta.noSessionInMock': 'En modo de prueba no hay sesión.',
    'cuenta.inviteToast': 'Cada persona se registra con su propio WhatsApp en comando.pro/app. Te copiamos el enlace.',
    'cuenta.waLinked': 'WhatsApp vinculado.',
  },
});

register({
  en: {
    'nav.hoy': 'Today', 'nav.agenda': 'Calendar', 'nav.crm': 'My CRM', 'nav.avisos': 'Alerts',
    'nav.marketing': 'Marketing', 'nav.cuenta': 'Account',
    'sub.hoy': 'What I do now.',
    'sub.agenda': 'Your reminders, visits and closes by day.',
    'sub.crm': 'How much money is in play and what is old, empty, duplicated or has no owner.',
    'sub.avisos': 'What Comando alerts you about, when it writes, and what else it can watch.',
    'sub.marketing': 'What your Facebook, Instagram and TikTok ads bring you, and what your analyst says.',
    'sub.cuenta': 'Your plan, your CRM, your team and what Comando knows about you.',
    'hoy.greet.morning': 'Good morning', 'hoy.greet.afternoon': 'Good afternoon', 'hoy.greet.evening': 'Good evening',
    'hoy.operator': 'there',
    'hoy.planWaiting': 'A plan is waiting for your <b>CONFIRM</b>',
    'hoy.planExpires': '{plan} · expires {when}',
    'hoy.waitingOwner': 'Waiting for the owner to approve · {when}',
    'hoy.tray': 'What I do now', 'hoy.trayWhat': 'The inbox',
    'hoy.nothingPending': 'Nothing pending', 'hoy.silenceIsGood': 'Silence is the good news.',
    'hoy.dependOnYou_one': '{n} thing depends on you. Tap it and carry on.',
    'hoy.dependOnYou_other': '{n} things depend on you. Tap one and carry on.',
    'hoy.whenSomething': 'When something depends on you, it shows up here.',
    'hoy.moneyInPlay': 'Money in play', 'hoy.openDeals': '{n} open deals', 'hoy.soonInAccount': 'Coming soon',
    'hoy.forToday': 'For today', 'hoy.task_one': 'task', 'hoy.task_other': 'tasks',
    'hoy.overdue_one': '{n} overdue', 'hoy.overdue_other': '{n} overdue', 'hoy.noneOverdue': 'None overdue',
    'hoy.waitingForYou': 'Waiting for you', 'hoy.pending_one': 'pending', 'hoy.pending_other': 'pending',
    'hoy.deserve_one': '{n} deserves your attention', 'hoy.deserve_other': '{n} deserve your attention',
    'hoy.nothingUrgent': 'Nothing urgent',
    'hoy.hello': '{greet}, {name} 👋',
    'hoy.youHave_one': 'You have <b>{n} thing</b> that depends on you.',
    'hoy.youHave_other': 'You have <b>{n} things</b> that depend on you.',
    'hoy.nothingUrgentNow': 'Nothing urgent for now.',
    'hoy.askByPhrase': 'Whatever you need, ask for it on WhatsApp in one sentence.',
    'hoy.review': 'What to review in your CRM', 'hoy.seeAll': 'See all',
    'hoy.last': 'The last thing you asked for', 'hoy.neverWrote': 'You have not written to Comando yet.',
    'hoy.undoLast': 'Undo the last one',
    'hoy.connectCrm': 'Connect your CRM and Comando starts working',
    'hoy.connectCrmSub': 'HubSpot, Salesforce or a Google sheet, with the system’s own login. Without a CRM you can already message it on WhatsApp; with one it sees your pipeline, alerts you and executes.',
    'hoy.connectCrmBtn': 'Connect my CRM',
    'agenda.allDay': 'All day', 'agenda.expectedClose': 'expected close', 'agenda.meeting': 'meeting',
    'agenda.nextStep': 'Next step', 'agenda.remindMe': 'Remind me', 'agenda.newReminder': 'New reminder',
    'agenda.list': 'List', 'agenda.month': 'Month',
    'agenda.pendingNote': 'For now you see your reminders. Expected closes and meetings from your CRM come soon.',
    'agenda.meanwhile': 'In the meantime:',
    'agenda.overdue': 'Overdue', 'agenda.today': 'Today', 'agenda.tomorrow': 'Tomorrow',
    'agenda.thisWeek': 'This week', 'agenda.later': 'Later on',
    'agenda.nothing30': 'Nothing in the next 30 days',
    'agenda.nothing30Sub': 'Tell Comando “remind me…” and it shows up here.',
    'agenda.what': 'The calendar', 'agenda.done': 'Done · {n}',
    'agenda.calDow': 'Mon,Tue,Wed,Thu,Fri,Sat,Sun',
    'agenda.prevMonth': 'Previous month', 'agenda.nextMonth': 'Next month', 'agenda.todayBtn': 'Today',
    'agenda.legendTask': 'Reminder', 'agenda.legendMeeting': 'Visit or meeting', 'agenda.legendClose': 'Expected close',
    'agenda.nothingThatDay': 'Nothing that day.',
    'crm.whatMoney': 'The money in play',
    'crm.wonMonth': 'Won this month', 'crm.lostMonth': 'Lost this month', 'crm.deals': '{n} deals',
    'crm.byStage': 'By stage', 'crm.upToDate': 'Up to date {when}', 'crm.askList': 'Ask for the list',
    'crm.by': 'By {field}',
    'crm.anyCut': 'Ask for any other cut: “by district”, “by property type”.',
    'crm.askCross': 'Ask for the cross',
    'crm.ownersNote': 'Your CRM has <b>{crmOwners} owner</b> loaded and Comando has <b>{people} people</b>: until the owner is set on each record, nothing tells apart who handles what.',
    'crm.whatToReview': 'What to review',
    'crm.neverDeletes': 'Comando detects; it never deletes or merges on its own.',
    'crm.seeList': 'See the list', 'crm.alertWeekly': 'Alert me every week',
    'crm.howInCrm': 'How you get it in your CRM:',
    'crm.of': 'of {of} ({pct} %)',
    'crm.contacts': 'Contacts',
    'avisos.turnOff': 'Switch off', 'avisos.pause': 'Pause', 'avisos.resume': 'Resume', 'avisos.change': 'Change',
    'avisos.changeDayHour': 'Change day or time',
    'avisos.times_one': 'once this week', 'avisos.times_other': '{n} times this week',
    'avisos.lastValue': 'last time: <b>{value}</b>', 'avisos.alertedYou': 'alerted you {when}',
    'avisos.sendsYou': 'Sends you “{title}”', 'avisos.byWhatsApp': 'on WhatsApp',
    'avisos.always': 'Always', 'avisos.whenSomething': 'When something happens', 'avisos.everySoOften': 'Every so often',
    'avisos.title': 'Comando alerts you when…',
    'avisos.watchesNothing': 'It watches nothing yet', 'avisos.watchesNothingSub': 'Tell it “alert me when…” or “every Monday…”.',
    'avisos.notListed': 'Some alerts are not listed here yet.', 'avisos.askHim': 'Ask it:',
    'avisos.replyWords': 'Every alert takes a WhatsApp reply: SEE, OK, LATER, STOP, WHY.',
    'avisos.newAlert': 'New alert',
    'avisos.schedule': 'Hours', 'avisos.dontWriteFrom': 'Do not write to me from', 'avisos.until': 'until',
    'avisos.dailyLimit': 'Most alerts per day',
    'avisos.proactive': 'Comando may write to me without being asked',
    'avisos.briefing': 'Morning summary', 'avisos.every': 'Every',
    'avisos.daily': 'day (Monday to Saturday)', 'avisos.weekly': 'Monday', 'avisos.monthly': 'month, on the first working day',
    'avisos.at': 'At', 'avisos.neverEmpty': 'It never arrives empty: if there is nothing, it does not write.',
    'avisos.dayOff': 'A day with no alerts?', 'avisos.scheduleWhat': 'The hours',
    'avisos.whenWrites': 'When it writes to you',
    'avisos.outsideHours': 'Anything outside those hours arrives first thing, marked “from last night”.',
    'avisos.ideas': 'Ideas to switch on with one sentence', 'avisos.ideasWhat': 'The ideas',
    'avisos.activate': 'Switch on', 'avisos.allActivated': 'You already switched on every idea.',
    'avisos.ideasSub': 'Comando turns it into an alert, shows you the preview and waits for your CONFIRM.',
    'avisos.prefsSaved': 'Done. It applies from the next alert.', 'avisos.done': 'Done.',
    'mk.vsPrev': '{sign}{pct} % vs. the previous period',
    'mk.connected': 'connected', 'mk.needsAuth': 'needs authorizing', 'mk.soon': 'soon',
    'mk.connectAnother': 'Connect another',
    'mk.spend': 'Spend · {period}', 'mk.leadsIn': 'Leads that came in',
    'mk.cpl': 'Cost per lead', 'mk.cpa': 'Cost per sale',
    'mk.sale_one': '{n} sale', 'mk.sale_other': '{n} sales',
    'mk.campaigns': 'Campaigns',
    'mk.spent': 'spent <b>{spend}</b>', 'mk.leadsAt': '<b>{leads}</b> leads at {cpl}',
    'mk.won_one': '{n} won', 'mk.won_other': '{n} won',
    'mk.raiseBudget': 'Raise budget', 'mk.seeLeads': 'See its leads',
    'mk.campaignsSub': 'Pausing or changing a budget goes through a preview and CONFIRM, like everything else.',
    'mk.analyst': 'Your analyst',
    'mk.reviewsWeekly': 'Reviews your campaigns every week · next: {when}',
    'mk.recommends': 'It recommends',
    'mk.impact': '{date} · impact {impact}', 'mk.apply': 'Apply',
    'mk.nothingPending': 'Nothing pending. The previous ones are applied.',
    'mk.underReview': 'Under review', 'mk.alreadyAsked': 'What you already asked',
    'mk.askHim': 'Ask them',
    'mk.funnel': 'From the ad to the sale',
    'mk.automations': 'What runs by itself',
    'mk.timesMonth_one': 'once this month', 'mk.timesMonth_other': '{n} times this month',
    'mk.new': 'New', 'mk.reports': 'Reports', 'mk.toWhatsApp': 'To WhatsApp',
    'mk.reportsSub': 'Weekly on Mondays, monthly on the first working day.', 'mk.askNow': 'Ask now',
    'mk.what': 'Marketing',
    'mk.extra': 'Connect your ad account and Comando starts following every lead through to the sale.',
    'mk.askOnWhatsApp': 'Ask on WhatsApp',
    'mk.connectSoon': 'Connecting ad accounts switches on soon. Write to us: hola@comando.pro',
    'mk.nextReview': 'You will see it in the next review.',
    'cuenta.plan': '{name} plan · US$ {price}/{interval}',
    'cuenta.month': 'mo', 'cuenta.year': 'yr',
    'cuenta.ofCommands': 'of {n} commands this month',
    'cuenta.over80': 'You passed 80 %.', 'cuenta.renews': 'Renews on {date}',
    'cuenta.usageWhat': 'Your usage', 'cuenta.yourPlan': 'Your plan: {plan}.',
    'cuenta.yourAccount': 'Your account', 'cuenta.edit': 'Edit',
    'cuenta.notLinked': 'Not linked', 'cuenta.youWriteTo': 'you message Comando at {number}',
    'cuenta.changeNumber': 'Change number', 'cuenta.changePlan': 'Change plan',
    'cuenta.yourCrm': 'Your CRM',
    'cuenta.mirror': '{contacts} contacts · {deals} deals within reach',
    'cuenta.crmSub': 'It connects with the CRM’s own login, without copying keys. Only the active CRM is queried when you talk to Comando.',
    'cuenta.adAccounts': 'Your ad accounts',
    'cuenta.noAdAccounts': 'No accounts connected',
    'cuenta.noAdAccountsSub': 'Meta (Facebook and Instagram) and TikTok Ads, with the same secure login.',
    'cuenta.forMarketing': 'For the Marketing section.', 'cuenta.connect': 'Connect', 'cuenta.authorize': 'Authorize',
    'cuenta.seeCampaigns': 'See campaigns',
    'cuenta.team': 'Your team',
    'role.owner': 'Owner', 'role.admin': 'Admin', 'role.supervisor': 'Supervisor', 'role.agent': 'Sales rep', 'role.analyst': 'Analyst',
    'cuenta.waUnverified': 'WhatsApp unverified', 'cuenta.changeRole': 'Change role',
    'cuenta.ownersNote': 'Your CRM has <b>{crmOwners} owner</b> loaded and here there are <b>{people}</b>. Until the owner is set on each record, “my deals” tells nobody apart.',
    'cuenta.teamWhat': 'Your team',
    'cuenta.teamExtra': 'Each person signs up with their own WhatsApp at comando.pro/app.',
    'cuenta.teamSub': 'Each person has their own WhatsApp and their own quota.', 'cuenta.invite': 'Invite',
    'cuenta.knows': 'What Comando knows about you', 'cuenta.forget': 'Forget',
    'cuenta.knowsNothing': 'Nothing yet. Tell it “for me a big deal starts at 300 thousand”.',
    'cuenta.knowsSub': 'It only learns what you tell it explicitly; never silently.',
    'cuenta.teachHim': 'Teach it something',
    'cuenta.privacy': 'Privacy and leaving',
    'cuenta.privacy1': 'Your data stays in your CRM; Comando keeps only the fields you switched on.',
    'cuenta.privacy2': 'What you write is kept for 90 days so failures can be diagnosed; nobody reads it without your request.',
    'cuenta.privacy3': 'It never messages your customers from your number: it prepares the message and you send it.',
    'cuenta.privacyPolicy': 'Privacy policy', 'cuenta.deleteAccount': 'Ask for my account to be deleted',
    'cuenta.signOut': 'Sign out',
    'cuenta.noSessionInMock': 'There is no session in demo mode.',
    'cuenta.inviteToast': 'Each person signs up with their own WhatsApp at comando.pro/app. We copied the link for you.',
    'cuenta.waLinked': 'WhatsApp linked.',
  },
});

register({
  pt: {
    'nav.hoy': 'Hoje', 'nav.agenda': 'Agenda', 'nav.crm': 'Meu CRM', 'nav.avisos': 'Avisos',
    'nav.marketing': 'Marketing', 'nav.cuenta': 'Conta',
    'sub.hoy': 'O que eu faço agora.',
    'sub.agenda': 'Seus lembretes, visitas e fechamentos por dia.',
    'sub.crm': 'Quanto dinheiro está em jogo e o que está velho, vazio, repetido ou sem dono.',
    'sub.avisos': 'Do que o Comando te avisa, quando ele escreve e o que mais pode vigiar.',
    'sub.marketing': 'O que seus anúncios do Facebook, Instagram e TikTok trazem, e o que o seu analista diz.',
    'sub.cuenta': 'Seu plano, seu CRM, seu time e o que o Comando sabe de você.',
    'hoy.greet.morning': 'Bom dia', 'hoy.greet.afternoon': 'Boa tarde', 'hoy.greet.evening': 'Boa noite',
    'hoy.operator': 'operador',
    'hoy.planWaiting': 'Um plano espera seu <b>CONFIRMAR</b>',
    'hoy.planExpires': '{plan} · vence {when}',
    'hoy.waitingOwner': 'Esperando o dono aprovar · {when}',
    'hoy.tray': 'O que eu faço agora', 'hoy.trayWhat': 'A caixa',
    'hoy.nothingPending': 'Nada pendente', 'hoy.silenceIsGood': 'O silêncio é a boa notícia.',
    'hoy.dependOnYou_one': '{n} coisa depende de você. Toque e siga.',
    'hoy.dependOnYou_other': '{n} coisas dependem de você. Toque uma e siga.',
    'hoy.whenSomething': 'Quando algo depender de você, aparece aqui.',
    'hoy.moneyInPlay': 'Dinheiro em jogo', 'hoy.openDeals': '{n} negócios abertos', 'hoy.soonInAccount': 'Entra em breve',
    'hoy.forToday': 'Para hoje', 'hoy.task_one': 'tarefa', 'hoy.task_other': 'tarefas',
    'hoy.overdue_one': '{n} vencida', 'hoy.overdue_other': '{n} vencidas', 'hoy.noneOverdue': 'Nenhuma vencida',
    'hoy.waitingForYou': 'Esperam você', 'hoy.pending_one': 'pendente', 'hoy.pending_other': 'pendentes',
    'hoy.deserve_one': '{n} merece sua atenção', 'hoy.deserve_other': '{n} merecem sua atenção',
    'hoy.nothingUrgent': 'Nada urgente',
    'hoy.hello': '{greet}, {name} 👋',
    'hoy.youHave_one': 'Você tem <b>{n} coisa</b> que depende de você.',
    'hoy.youHave_other': 'Você tem <b>{n} coisas</b> que dependem de você.',
    'hoy.nothingUrgentNow': 'Nada urgente por enquanto.',
    'hoy.askByPhrase': 'O que precisar, peça pelo WhatsApp com uma frase.',
    'hoy.review': 'O que revisar no seu CRM', 'hoy.seeAll': 'Ver tudo',
    'hoy.last': 'A última coisa que você pediu', 'hoy.neverWrote': 'Você ainda não escreveu para o Comando.',
    'hoy.undoLast': 'Desfazer a última',
    'hoy.connectCrm': 'Conecte seu CRM e o Comando começa a trabalhar',
    'hoy.connectCrmSub': 'HubSpot, Salesforce ou uma planilha do Google, com o login do próprio sistema. Sem CRM você já pode escrever pelo WhatsApp; com CRM ele vê seu funil, te avisa e executa.',
    'hoy.connectCrmBtn': 'Conectar meu CRM',
    'agenda.allDay': 'Dia todo', 'agenda.expectedClose': 'fechamento previsto', 'agenda.meeting': 'reunião',
    'agenda.nextStep': 'Próximo passo', 'agenda.remindMe': 'Me lembrar', 'agenda.newReminder': 'Novo lembrete',
    'agenda.list': 'Lista', 'agenda.month': 'Mês',
    'agenda.pendingNote': 'Por enquanto você vê seus lembretes. Os fechamentos previstos e as reuniões do seu CRM entram em breve.',
    'agenda.meanwhile': 'Enquanto isso:',
    'agenda.overdue': 'Vencidas', 'agenda.today': 'Hoje', 'agenda.tomorrow': 'Amanhã',
    'agenda.thisWeek': 'Esta semana', 'agenda.later': 'Mais para frente',
    'agenda.nothing30': 'Nada nos próximos 30 dias',
    'agenda.nothing30Sub': 'Peça ao Comando «me lembra…» e aparece aqui.',
    'agenda.what': 'A agenda', 'agenda.done': 'Feitas · {n}',
    'agenda.calDow': 'seg,ter,qua,qui,sex,sáb,dom',
    'agenda.prevMonth': 'Mês anterior', 'agenda.nextMonth': 'Próximo mês', 'agenda.todayBtn': 'Hoje',
    'agenda.legendTask': 'Lembrete', 'agenda.legendMeeting': 'Visita ou reunião', 'agenda.legendClose': 'Fechamento previsto',
    'agenda.nothingThatDay': 'Nada nesse dia.',
    'crm.whatMoney': 'O dinheiro em jogo',
    'crm.wonMonth': 'Ganho este mês', 'crm.lostMonth': 'Perdido este mês', 'crm.deals': '{n} negócios',
    'crm.byStage': 'Por etapa', 'crm.upToDate': 'Em dia {when}', 'crm.askList': 'Pedir a lista',
    'crm.by': 'Por {field}',
    'crm.anyCut': 'Peça qualquer outro corte: «por bairro», «por tipo de imóvel».',
    'crm.askCross': 'Pedir o cruzamento',
    'crm.ownersNote': 'Seu CRM tem <b>{crmOwners} dono</b> cadastrado e no Comando são <b>{people} pessoas</b>: enquanto não colocarem o dono em cada registro, nada vai distinguir quem cuida do quê.',
    'crm.whatToReview': 'O que revisar',
    'crm.neverDeletes': 'O Comando detecta; nunca apaga nem junta por conta própria.',
    'crm.seeList': 'Ver a lista', 'crm.alertWeekly': 'Me avisar toda semana',
    'crm.howInCrm': 'Como você tira isso no seu CRM:',
    'crm.of': 'de {of} ({pct} %)',
    'crm.contacts': 'Contatos',
    'avisos.turnOff': 'Desligar', 'avisos.pause': 'Pausar', 'avisos.resume': 'Retomar', 'avisos.change': 'Mudar',
    'avisos.changeDayHour': 'Mudar dia ou hora',
    'avisos.times_one': '1 vez esta semana', 'avisos.times_other': '{n} vezes esta semana',
    'avisos.lastValue': 'da última vez: <b>{value}</b>', 'avisos.alertedYou': 'te avisou {when}',
    'avisos.sendsYou': 'Te manda «{title}»', 'avisos.byWhatsApp': 'pelo WhatsApp',
    'avisos.always': 'Sempre', 'avisos.whenSomething': 'Quando algo acontece', 'avisos.everySoOften': 'De tempos em tempos',
    'avisos.title': 'O Comando te avisa quando…',
    'avisos.watchesNothing': 'Ainda não vigia nada', 'avisos.watchesNothingSub': 'Diga «me avisa quando…» ou «toda segunda…».',
    'avisos.notListed': 'Alguns avisos ainda não aparecem aqui.', 'avisos.askHim': 'Pergunte:',
    'avisos.replyWords': 'Todo aviso aceita resposta pelo WhatsApp: VER, OK, DEPOIS, CHEGA, POR QUÊ.',
    'avisos.newAlert': 'Novo aviso',
    'avisos.schedule': 'Horário', 'avisos.dontWriteFrom': 'Não me escreva das', 'avisos.until': 'até',
    'avisos.dailyLimit': 'Máximo de avisos por dia',
    'avisos.proactive': 'O Comando pode me escrever sem eu pedir',
    'avisos.briefing': 'Resumo da manhã', 'avisos.every': 'Cada',
    'avisos.daily': 'dia (segunda a sábado)', 'avisos.weekly': 'segunda', 'avisos.monthly': 'mês, no primeiro dia útil',
    'avisos.at': 'Às', 'avisos.neverEmpty': 'Nunca chega vazio: se não há nada, ele não escreve.',
    'avisos.dayOff': 'Um dia sem avisos?', 'avisos.scheduleWhat': 'O horário',
    'avisos.whenWrites': 'Quando ele te escreve',
    'avisos.outsideHours': 'O que cai fora do horário chega logo cedo, marcado como «de ontem à noite».',
    'avisos.ideas': 'Ideias para ligar com uma frase', 'avisos.ideasWhat': 'As ideias',
    'avisos.activate': 'Ligar', 'avisos.allActivated': 'Você já ligou todas as ideias.',
    'avisos.ideasSub': 'O Comando transforma em aviso, mostra a prévia e espera seu CONFIRMAR.',
    'avisos.prefsSaved': 'Pronto. Vale a partir do próximo aviso.', 'avisos.done': 'Pronto.',
    'mk.vsPrev': '{sign}{pct} % vs. o período anterior',
    'mk.connected': 'conectada', 'mk.needsAuth': 'falta autorizar', 'mk.soon': 'em breve',
    'mk.connectAnother': 'Conectar outra',
    'mk.spend': 'Investimento · {period}', 'mk.leadsIn': 'Leads que entraram',
    'mk.cpl': 'Custo por lead', 'mk.cpa': 'Custo por venda',
    'mk.sale_one': '{n} venda', 'mk.sale_other': '{n} vendas',
    'mk.campaigns': 'Campanhas',
    'mk.spent': 'gastou <b>{spend}</b>', 'mk.leadsAt': '<b>{leads}</b> leads a {cpl}',
    'mk.won_one': '{n} ganho', 'mk.won_other': '{n} ganhos',
    'mk.raiseBudget': 'Subir orçamento', 'mk.seeLeads': 'Ver os leads dela',
    'mk.campaignsSub': 'Pausar ou mudar orçamento passa por prévia e CONFIRMAR, como tudo.',
    'mk.analyst': 'Seu analista',
    'mk.reviewsWeekly': 'Revisa suas campanhas toda semana · próxima: {when}',
    'mk.recommends': 'Ele recomenda',
    'mk.impact': '{date} · impacto {impact}', 'mk.apply': 'Aplicar',
    'mk.nothingPending': 'Nada pendente. O anterior já está aplicado.',
    'mk.underReview': 'Em análise', 'mk.alreadyAsked': 'O que você já perguntou',
    'mk.askHim': 'Perguntar',
    'mk.funnel': 'Do anúncio à venda',
    'mk.automations': 'O que roda sozinho',
    'mk.timesMonth_one': '1 vez este mês', 'mk.timesMonth_other': '{n} vezes este mês',
    'mk.new': 'Nova', 'mk.reports': 'Relatórios', 'mk.toWhatsApp': 'No WhatsApp',
    'mk.reportsSub': 'Semanal nas segundas, mensal no primeiro dia útil.', 'mk.askNow': 'Pedir agora',
    'mk.what': 'Marketing',
    'mk.extra': 'Conecte sua conta de anúncios e o Comando começa a seguir cada lead até a venda.',
    'mk.askOnWhatsApp': 'Perguntar pelo WhatsApp',
    'mk.connectSoon': 'A conexão de contas de anúncios entra em breve. Escreva para nós: hola@comando.pro',
    'mk.nextReview': 'Você vai ver na próxima revisão.',
    'cuenta.plan': 'Plano {name} · US$ {price}/{interval}',
    'cuenta.month': 'mês', 'cuenta.year': 'ano',
    'cuenta.ofCommands': 'de {n} comandos este mês',
    'cuenta.over80': 'Você passou dos 80 %.', 'cuenta.renews': 'Renova em {date}',
    'cuenta.usageWhat': 'O consumo', 'cuenta.yourPlan': 'Seu plano: {plan}.',
    'cuenta.yourAccount': 'Sua conta', 'cuenta.edit': 'Editar',
    'cuenta.notLinked': 'Sem vincular', 'cuenta.youWriteTo': 'você escreve para o Comando no {number}',
    'cuenta.changeNumber': 'Mudar número', 'cuenta.changePlan': 'Mudar de plano',
    'cuenta.yourCrm': 'Seu CRM',
    'cuenta.mirror': '{contacts} contatos · {deals} negócios ao seu alcance',
    'cuenta.crmSub': 'Conecta com o login do próprio CRM, sem copiar chaves. Só o CRM ativo é consultado quando você fala com o Comando.',
    'cuenta.adAccounts': 'Suas contas de anúncios',
    'cuenta.noAdAccounts': 'Sem contas conectadas',
    'cuenta.noAdAccountsSub': 'Meta (Facebook e Instagram) e TikTok Ads, com o mesmo login seguro.',
    'cuenta.forMarketing': 'Para a seção Marketing.', 'cuenta.connect': 'Conectar', 'cuenta.authorize': 'Autorizar',
    'cuenta.seeCampaigns': 'Ver campanhas',
    'cuenta.team': 'Seu time',
    'role.owner': 'Dono', 'role.admin': 'Admin', 'role.supervisor': 'Supervisor', 'role.agent': 'Vendedor', 'role.analyst': 'Analista',
    'cuenta.waUnverified': 'WhatsApp sem verificar', 'cuenta.changeRole': 'Mudar papel',
    'cuenta.ownersNote': 'Seu CRM tem <b>{crmOwners} dono</b> cadastrado e aqui são <b>{people}</b>. Até colocarem o dono em cada registro, «meus negócios» não distingue ninguém.',
    'cuenta.teamWhat': 'Seu time',
    'cuenta.teamExtra': 'Cada pessoa se cadastra com o próprio WhatsApp em comando.pro/app.',
    'cuenta.teamSub': 'Cada pessoa tem o próprio WhatsApp e a própria cota.', 'cuenta.invite': 'Convidar',
    'cuenta.knows': 'O que o Comando sabe de você', 'cuenta.forget': 'Esquecer',
    'cuenta.knowsNothing': 'Ainda nada. Diga «para mim um negócio grande começa em 300 mil».',
    'cuenta.knowsSub': 'Só aprende o que você diz explicitamente; nunca em silêncio.',
    'cuenta.teachHim': 'Ensinar algo',
    'cuenta.privacy': 'Privacidade e saída',
    'cuenta.privacy1': 'Seus dados ficam no seu CRM; o Comando guarda só os campos que você ligou.',
    'cuenta.privacy2': 'O que você escreve fica 90 dias para diagnosticar falhas; ninguém lê sem você pedir.',
    'cuenta.privacy3': 'Ele nunca escreve para seus clientes pelo seu número: prepara a mensagem e você envia.',
    'cuenta.privacyPolicy': 'Política de privacidade', 'cuenta.deleteAccount': 'Pedir a exclusão da minha conta',
    'cuenta.signOut': 'Sair da conta',
    'cuenta.noSessionInMock': 'No modo de teste não há sessão.',
    'cuenta.inviteToast': 'Cada pessoa se cadastra com o próprio WhatsApp em comando.pro/app. Copiamos o link para você.',
    'cuenta.waLinked': 'WhatsApp vinculado.',
  },
});

/* ==================================== puesta en marcha: WhatsApp y el CRM */
register({
  es: {
    'setup.step1': '1 Cuenta', 'setup.step2': '2 WhatsApp', 'setup.step3': '3 CRM',
    'setup.wa.title': 'Vincula tu WhatsApp',
    'setup.wa.hint': 'Comando funciona desde tu propio WhatsApp. Escribe el número desde el que le vas a hablar.',
    'setup.wa.locale': 'Idioma de las respuestas',
    'setup.wa.localeFailed': 'No pude guardar el idioma. Inténtalo de nuevo.',
    'setup.wa.noPicker': 'No se pudo cargar el selector de país. Recarga la página.',
    'setup.wa.sendThis': 'Envía este mensaje <b>desde el número que registraste</b> al WhatsApp de Comando ({number}):',
    'setup.wa.open': 'Abrir WhatsApp y enviar',
    'setup.wa.waiting': 'El código vence en 15 minutos. Esperando tu mensaje…',
    'setup.wa.change': 'Cambiar número',
    'setup.wa.foot': 'Luego podrás conectar HubSpot, Salesforce o una hoja de Google desde tu cuenta. No hace falta para empezar.',
    'crm.soon': 'Próximamente', 'crm.connected': 'Conectado', 'crm.connect': 'Conectar',
    'crm.connectFromScratch': 'Conectar desde cero', 'crm.disconnectActive': 'Desconecta el CRM activo',
    'crm.confirming': 'Confirmando la conexión con {name}…',
    'crm.onlyThis': '{name} conectado. Comando solo consulta este CRM.',
    'crm.noneConnected': 'No hay un CRM conectado. Puedes recuperar el anterior o vincular uno nuevo.',
    'crm.unlinked': '<b>{name} está desvinculado.</b> Guardamos tu copia hasta el {date}; si lo vuelves a autorizar antes, recuperas la configuración y los datos.',
    'crm.relink': 'Volver a vincular y recuperar', 'crm.purgeNow': 'Eliminar datos ahora',
    'crm.whatCanSee': 'Qué puede consultar Comando', 'crm.disconnect': 'Desconectar {name}',
    'crm.mockOauth': 'En modo de prueba no se abre la autorización de {name}.',
    'crm.noSession': 'No recibimos la sesión de conexión',
    'crm.authorizeIn': 'Autoriza el acceso en la ventana de {name}… (esta página se actualiza sola)',
    'crm.authTimeout': 'No se completó la autorización. Vuelve a intentarlo.',
    'crm.recovered': '{name} recuperado. Comando reactivó tu copia.',
    'crm.connectedToast': '{name} conectado. Comando está importando tus datos.',
    'crm.googleLoadFailed': 'No se pudo cargar {what}. Revisa tu conexión y vuelve a intentar.',
    'crm.googleNoGrant': 'Google no devolvió el permiso', 'crm.googleCancelled': 'Se canceló el permiso de Google',
    'crm.confirmDisconnect': '¿Desconectar {name}? Comando deja de consultarlo al instante. La copia se borra sola en 7 días.',
    'crm.confirmPurge': '¿Eliminar ahora la copia de {name}? No se puede deshacer.',
    'crm.purged': 'La copia de {name} fue eliminada.',
    'crm.purgeBlocked': 'No se completó: hay una retención legal activa.',
    'crm.sheetConnected': 'Hoja conectada. Comando la está leyendo.',
    'crm.sheetsConnected': '{n} hojas conectadas.',
  },
  en: {
    'setup.step1': '1 Account', 'setup.step2': '2 WhatsApp', 'setup.step3': '3 CRM',
    'setup.wa.title': 'Link your WhatsApp',
    'setup.wa.hint': 'Comando works from your own WhatsApp. Write the number you will message it from.',
    'setup.wa.locale': 'Language of the replies',
    'setup.wa.localeFailed': 'I could not save the language. Try again.',
    'setup.wa.noPicker': 'The country picker did not load. Reload the page.',
    'setup.wa.sendThis': 'Send this message <b>from the number you registered</b> to Comando’s WhatsApp ({number}):',
    'setup.wa.open': 'Open WhatsApp and send',
    'setup.wa.waiting': 'The code expires in 15 minutes. Waiting for your message…',
    'setup.wa.change': 'Change number',
    'setup.wa.foot': 'Later you can connect HubSpot, Salesforce or a Google sheet from your account. You do not need it to start.',
    'crm.soon': 'Coming soon', 'crm.connected': 'Connected', 'crm.connect': 'Connect',
    'crm.connectFromScratch': 'Connect from scratch', 'crm.disconnectActive': 'Disconnect the active CRM',
    'crm.confirming': 'Confirming the connection with {name}…',
    'crm.onlyThis': '{name} connected. Comando only queries this CRM.',
    'crm.noneConnected': 'No CRM is connected. You can recover the previous one or link a new one.',
    'crm.unlinked': '<b>{name} is unlinked.</b> We keep your copy until {date}; if you authorize it again before then, you get the settings and the data back.',
    'crm.relink': 'Link again and recover', 'crm.purgeNow': 'Delete the data now',
    'crm.whatCanSee': 'What Comando can query', 'crm.disconnect': 'Disconnect {name}',
    'crm.mockOauth': 'In demo mode the {name} authorization does not open.',
    'crm.noSession': 'We did not get the connection session',
    'crm.authorizeIn': 'Authorize access in the {name} window… (this page refreshes on its own)',
    'crm.authTimeout': 'The authorization did not complete. Try again.',
    'crm.recovered': '{name} recovered. Comando switched your copy back on.',
    'crm.connectedToast': '{name} connected. Comando is importing your data.',
    'crm.googleLoadFailed': 'Could not load {what}. Check your connection and try again.',
    'crm.googleNoGrant': 'Google did not return the permission', 'crm.googleCancelled': 'The Google permission was cancelled',
    'crm.confirmDisconnect': 'Disconnect {name}? Comando stops querying it at once. The copy deletes itself in 7 days.',
    'crm.confirmPurge': 'Delete the {name} copy now? This cannot be undone.',
    'crm.purged': 'The {name} copy was deleted.',
    'crm.purgeBlocked': 'It did not complete: there is a legal hold in place.',
    'crm.sheetConnected': 'Sheet connected. Comando is reading it.',
    'crm.sheetsConnected': '{n} sheets connected.',
  },
  pt: {
    'setup.step1': '1 Conta', 'setup.step2': '2 WhatsApp', 'setup.step3': '3 CRM',
    'setup.wa.title': 'Vincule seu WhatsApp',
    'setup.wa.hint': 'O Comando funciona pelo seu próprio WhatsApp. Escreva o número de onde você vai falar com ele.',
    'setup.wa.locale': 'Idioma das respostas',
    'setup.wa.localeFailed': 'Não consegui salvar o idioma. Tente de novo.',
    'setup.wa.noPicker': 'Não deu para carregar o seletor de país. Recarregue a página.',
    'setup.wa.sendThis': 'Envie esta mensagem <b>do número que você cadastrou</b> para o WhatsApp do Comando ({number}):',
    'setup.wa.open': 'Abrir o WhatsApp e enviar',
    'setup.wa.waiting': 'O código vence em 15 minutos. Esperando sua mensagem…',
    'setup.wa.change': 'Mudar número',
    'setup.wa.foot': 'Depois você conecta HubSpot, Salesforce ou uma planilha do Google pela sua conta. Não precisa para começar.',
    'crm.soon': 'Em breve', 'crm.connected': 'Conectado', 'crm.connect': 'Conectar',
    'crm.connectFromScratch': 'Conectar do zero', 'crm.disconnectActive': 'Desconecte o CRM ativo',
    'crm.confirming': 'Confirmando a conexão com {name}…',
    'crm.onlyThis': '{name} conectado. O Comando consulta só este CRM.',
    'crm.noneConnected': 'Não há CRM conectado. Você pode recuperar o anterior ou vincular um novo.',
    'crm.unlinked': '<b>{name} está desvinculado.</b> Guardamos sua cópia até {date}; se você autorizar de novo antes disso, recupera a configuração e os dados.',
    'crm.relink': 'Vincular de novo e recuperar', 'crm.purgeNow': 'Apagar os dados agora',
    'crm.whatCanSee': 'O que o Comando pode consultar', 'crm.disconnect': 'Desconectar {name}',
    'crm.mockOauth': 'No modo de teste a autorização do {name} não abre.',
    'crm.noSession': 'Não recebemos a sessão de conexão',
    'crm.authorizeIn': 'Autorize o acesso na janela do {name}… (esta página se atualiza sozinha)',
    'crm.authTimeout': 'A autorização não foi concluída. Tente de novo.',
    'crm.recovered': '{name} recuperado. O Comando reativou sua cópia.',
    'crm.connectedToast': '{name} conectado. O Comando está importando seus dados.',
    'crm.googleLoadFailed': 'Não deu para carregar {what}. Confira sua conexão e tente de novo.',
    'crm.googleNoGrant': 'O Google não devolveu a permissão', 'crm.googleCancelled': 'A permissão do Google foi cancelada',
    'crm.confirmDisconnect': 'Desconectar {name}? O Comando para de consultar na hora. A cópia se apaga sozinha em 7 dias.',
    'crm.confirmPurge': 'Apagar agora a cópia do {name}? Não dá para desfazer.',
    'crm.purged': 'A cópia do {name} foi apagada.',
    'crm.purgeBlocked': 'Não foi concluído: há uma retenção legal ativa.',
    'crm.sheetConnected': 'Planilha conectada. O Comando está lendo.',
    'crm.sheetsConnected': '{n} planilhas conectadas.',
  },
});
