/**
 * Los textos de «Qué puede consultar Comando», en los tres idiomas.
 *
 * Diccionario propio y no un bloque más en `../strings.js` por una razón de
 * peso, literal: el del panel son 609 claves (~60 KB) y esta pantalla usa 66.
 * `register()` está hecho para llamarse desde varios módulos —fusiona en la
 * misma tabla—, así que `t()` funciona igual, la garantía de los tres idiomas
 * es la misma (`check-app-i18n.mjs` la comprueba archivo por archivo) y esta
 * página, que se abre de vez en cuando desde un botón, no arrastra el
 * vocabulario entero del panel para pintar cuatro pestañas.
 *
 * Lo que NO se traduce: el nombre interno de cada propiedad (`hs_lead_status`)
 * y su etiqueta, que son del CRM del cliente y ya están en su idioma.
 */
import { register } from '../i18n.js?v=1';

register({
  es: {
    /* ------------------------------------------------- marco de la página */
    'db.title': 'Comando — Qué puede consultar',
    'db.back': 'Mi cuenta',
    'db.h1': 'Qué puede consultar Comando',
    'db.intro': 'Elige qué campos de tu CRM puede leer y cuáles puede modificar cuando le escribes por WhatsApp. Lo que dejes apagado, Comando no lo consulta ni lo copia.',
    'db.loading': 'Leyendo los campos de tu CRM…',
    'db.tabs': 'Tipo de registro',
    'db.foot': 'Los cambios se guardan solos. Los campos marcados como {what} se consultan en vivo en tu CRM cada vez que hacen falta.',
    'db.footSensitive': 'sensibles',
    /* ------------------------------------------------------- las pantallas */
    'db.signin.title': 'Inicia sesión para ver tus campos',
    'db.signin.sub': 'Esta página usa la misma cuenta con la que registraste tu WhatsApp.',
    'db.signin.btn': 'Iniciar sesión',
    'db.nocrm.title': 'Primero conecta tu CRM',
    'db.nocrm.sub': 'Cuando conectes tu CRM desde el panel, aquí aparecerán todos tus campos para que elijas cuáles puede consultar Comando.',
    'db.nocrm.btn': 'Conectar mi CRM',
    'db.error.title': 'No pudimos cargar tus campos',
    'db.error.retry': 'Reintentar',
    'db.error.back': 'Volver',
    'db.error.generic': 'Vuelve a intentarlo en unos segundos.',
    'db.error.session': 'No se pudo cargar la sesión.',
    'db.error.notEnabled': 'Esta función todavía no está habilitada en tu cuenta. Escríbenos a hola@comando.pro si la necesitas ya.',
    'db.error.read': 'No pudimos leer los campos de tu CRM.',
    /* ------------------------------------------- objetos, listas y buscador */
    'db.obj.contact': 'Contactos', 'db.obj.deal': 'Negocios', 'db.obj.company': 'Empresas', 'db.obj.order': 'Pedidos',
    'db.tabCount': '{on} activos de {total}',
    'db.noFields': 'Todavía no leímos campos de este tipo en tu CRM.',
    'db.active': 'Activos',
    'db.activeHint': 'Lo que Comando puede consultar hoy. Los marcados como «siempre disponible» no se pueden apagar: sin ellos no podría identificar un registro.',
    'db.noneActive': 'Todavía no activaste ningún campo.',
    'db.suggested': 'Sugeridos',
    'db.suggestedHint': 'Los que más te harían falta, según lo que ya le pediste y qué tan llenos están.',
    'db.nothingToSuggest': 'Ya activaste todo lo que teníamos para sugerirte.',
    'db.all': 'Todos los campos',
    'db.search': 'Buscar por nombre o nombre interno…',
    'db.searchAria': 'Buscar campos',
    'db.noMatch': 'No encontramos ningún campo que coincida con «{q}».',
    'db.clearSearch': 'Borrar la búsqueda',
    'db.showMore': 'Mostrar {n} más (quedan {rest})',
    /* --------------------------------------------------- una fila de campo */
    'db.query': 'Consultar', 'db.edit': 'Editar',
    'db.tagCore': 'siempre disponible',
    'db.tagSensitive': 'sensible — se consulta en vivo',
    'db.noName': 'Campo sin nombre',
    'db.opts': '{n} opciones',
    /* Los tipos del CRM en palabras del operador, no del esquema. */
    'db.type.text': 'texto', 'db.type.textLong': 'texto largo', 'db.type.list': 'lista desplegable',
    'db.type.multi': 'lista de opciones', 'db.type.number': 'número', 'db.type.date': 'fecha',
    'db.type.datetime': 'fecha y hora', 'db.type.bool': 'sí / no', 'db.type.phone': 'teléfono',
    'db.type.email': 'correo', 'db.type.url': 'enlace', 'db.type.file': 'archivo',
    'db.type.json': 'datos', 'db.type.other': 'otro',
    /* ------------------------------------------ por qué sugerimos un campo */
    'db.why.asked_one': 'lo pediste {n} vez',
    'db.why.asked_other': 'lo pediste {n} veces',
    'db.why.askedWhen': '{asked}, la última {when}',
    'db.why.fill': 'está lleno en el {pct} % de tus registros',
    'db.why.options': 'lista con {n} opciones en tu CRM',
    'db.why.standard': 'campo estándar de tu CRM',
    'db.when.today': 'hoy', 'db.when.yesterday': 'ayer',
    'db.when.days': 'hace {n} días', 'db.when.month': 'hace un mes', 'db.when.months': 'hace {n} meses',
    /* ----------------------------------------------------------- guardado */
    'db.noteLive': 'Comando lo consultará en vivo en tu CRM cada vez que lo necesite.',
    'db.noteMirror': 'Comando ya puede consultarlo; los datos históricos se completan en unos minutos.',
    'db.saveFailed': 'No se pudo guardar.',
    'db.saveError': 'No se guardó: {msg} Inténtalo de nuevo.',
    'db.sayOn': '{field}: activado.',
    'db.sayOff': '{field}: desactivado.',
    'db.sayFailed': 'No se pudo guardar {field}.',
  },
  en: {
    'db.title': 'Comando — What it can look up',
    'db.back': 'My account',
    'db.h1': 'What Comando can look up',
    'db.intro': 'Choose which CRM fields it can read and which ones it can change when you message it on WhatsApp. Anything you leave off, Comando neither reads nor copies.',
    'db.loading': 'Reading the fields in your CRM…',
    'db.tabs': 'Record type',
    'db.foot': 'Changes save on their own. Fields marked as {what} are read live from your CRM every time they are needed.',
    'db.footSensitive': 'sensitive',
    'db.signin.title': 'Sign in to see your fields',
    'db.signin.sub': 'This page uses the same account you registered your WhatsApp with.',
    'db.signin.btn': 'Sign in',
    'db.nocrm.title': 'Connect your CRM first',
    'db.nocrm.sub': 'Once you connect your CRM from the panel, all your fields will show up here so you can choose which ones Comando may look up.',
    'db.nocrm.btn': 'Connect my CRM',
    'db.error.title': 'We could not load your fields',
    'db.error.retry': 'Try again',
    'db.error.back': 'Back',
    'db.error.generic': 'Try again in a few seconds.',
    'db.error.session': 'We could not load the session.',
    'db.error.notEnabled': 'This feature is not switched on in your account yet. Write to hola@comando.pro if you need it now.',
    'db.error.read': 'We could not read the fields in your CRM.',
    'db.obj.contact': 'Contacts', 'db.obj.deal': 'Deals', 'db.obj.company': 'Companies', 'db.obj.order': 'Orders',
    'db.tabCount': '{on} on out of {total}',
    'db.noFields': 'We have not read any field of this type in your CRM yet.',
    'db.active': 'On',
    'db.activeHint': 'What Comando can look up today. The ones marked “always available” cannot be switched off: without them it could not tell one record from another.',
    'db.noneActive': 'You have not switched on any field yet.',
    'db.suggested': 'Suggested',
    'db.suggestedHint': 'The ones you would miss the most, going by what you have already asked for and how filled in they are.',
    'db.nothingToSuggest': 'You already switched on everything we had to suggest.',
    'db.all': 'All fields',
    'db.search': 'Search by name or internal name…',
    'db.searchAria': 'Search fields',
    'db.noMatch': 'We found no field matching “{q}”.',
    'db.clearSearch': 'Clear the search',
    'db.showMore': 'Show {n} more ({rest} left)',
    'db.query': 'Look up', 'db.edit': 'Edit',
    'db.tagCore': 'always available',
    'db.tagSensitive': 'sensitive — read live',
    'db.noName': 'Field with no name',
    'db.opts': '{n} options',
    'db.type.text': 'text', 'db.type.textLong': 'long text', 'db.type.list': 'dropdown list',
    'db.type.multi': 'multiple choice', 'db.type.number': 'number', 'db.type.date': 'date',
    'db.type.datetime': 'date and time', 'db.type.bool': 'yes / no', 'db.type.phone': 'phone',
    'db.type.email': 'email', 'db.type.url': 'link', 'db.type.file': 'file',
    'db.type.json': 'data', 'db.type.other': 'other',
    'db.why.asked_one': 'you asked for it {n} time',
    'db.why.asked_other': 'you asked for it {n} times',
    'db.why.askedWhen': '{asked}, the last one {when}',
    'db.why.fill': 'it is filled in on {pct} % of your records',
    'db.why.options': 'a list with {n} options in your CRM',
    'db.why.standard': 'a standard field in your CRM',
    'db.when.today': 'today', 'db.when.yesterday': 'yesterday',
    'db.when.days': '{n} days ago', 'db.when.month': 'a month ago', 'db.when.months': '{n} months ago',
    'db.noteLive': 'Comando will read it live from your CRM every time it needs it.',
    'db.noteMirror': 'Comando can look it up now; past data fills in over the next few minutes.',
    'db.saveFailed': 'It could not be saved.',
    'db.saveError': 'Not saved: {msg} Try again.',
    'db.sayOn': '{field}: on.',
    'db.sayOff': '{field}: off.',
    'db.sayFailed': 'Could not save {field}.',
  },
  pt: {
    'db.title': 'Comando — O que ele pode consultar',
    'db.back': 'Minha conta',
    'db.h1': 'O que o Comando pode consultar',
    'db.intro': 'Escolha quais campos do seu CRM ele pode ler e quais pode alterar quando você escreve pelo WhatsApp. O que você deixar desligado, o Comando não consulta nem copia.',
    'db.loading': 'Lendo os campos do seu CRM…',
    'db.tabs': 'Tipo de registro',
    'db.foot': 'As mudanças salvam sozinhas. Os campos marcados como {what} são consultados ao vivo no seu CRM sempre que fazem falta.',
    'db.footSensitive': 'sensíveis',
    'db.signin.title': 'Entre para ver seus campos',
    'db.signin.sub': 'Esta página usa a mesma conta com que você cadastrou seu WhatsApp.',
    'db.signin.btn': 'Entrar',
    'db.nocrm.title': 'Primeiro conecte seu CRM',
    'db.nocrm.sub': 'Quando você conectar seu CRM pelo painel, todos os seus campos aparecerão aqui para você escolher quais o Comando pode consultar.',
    'db.nocrm.btn': 'Conectar meu CRM',
    'db.error.title': 'Não conseguimos carregar seus campos',
    'db.error.retry': 'Tentar de novo',
    'db.error.back': 'Voltar',
    'db.error.generic': 'Tente de novo em alguns segundos.',
    'db.error.session': 'Não foi possível carregar a sessão.',
    'db.error.notEnabled': 'Esta função ainda não está habilitada na sua conta. Escreva para hola@comando.pro se precisar dela já.',
    'db.error.read': 'Não conseguimos ler os campos do seu CRM.',
    'db.obj.contact': 'Contatos', 'db.obj.deal': 'Negócios', 'db.obj.company': 'Empresas', 'db.obj.order': 'Pedidos',
    'db.tabCount': '{on} ativos de {total}',
    'db.noFields': 'Ainda não lemos nenhum campo desse tipo no seu CRM.',
    'db.active': 'Ativos',
    'db.activeHint': 'O que o Comando pode consultar hoje. Os marcados como «sempre disponível» não dá para desligar: sem eles ele não conseguiria identificar um registro.',
    'db.noneActive': 'Você ainda não ativou nenhum campo.',
    'db.suggested': 'Sugeridos',
    'db.suggestedHint': 'Os que mais fariam falta, pelo que você já pediu e pelo quanto estão preenchidos.',
    'db.nothingToSuggest': 'Você já ativou tudo o que tínhamos para sugerir.',
    'db.all': 'Todos os campos',
    'db.search': 'Buscar por nome ou nome interno…',
    'db.searchAria': 'Buscar campos',
    'db.noMatch': 'Não encontramos nenhum campo que combine com «{q}».',
    'db.clearSearch': 'Limpar a busca',
    'db.showMore': 'Mostrar mais {n} (faltam {rest})',
    'db.query': 'Consultar', 'db.edit': 'Editar',
    'db.tagCore': 'sempre disponível',
    'db.tagSensitive': 'sensível — consultado ao vivo',
    'db.noName': 'Campo sem nome',
    'db.opts': '{n} opções',
    'db.type.text': 'texto', 'db.type.textLong': 'texto longo', 'db.type.list': 'lista suspensa',
    'db.type.multi': 'lista de opções', 'db.type.number': 'número', 'db.type.date': 'data',
    'db.type.datetime': 'data e hora', 'db.type.bool': 'sim / não', 'db.type.phone': 'telefone',
    'db.type.email': 'e-mail', 'db.type.url': 'link', 'db.type.file': 'arquivo',
    'db.type.json': 'dados', 'db.type.other': 'outro',
    'db.why.asked_one': 'você pediu {n} vez',
    'db.why.asked_other': 'você pediu {n} vezes',
    'db.why.askedWhen': '{asked}, a última {when}',
    'db.why.fill': 'está preenchido em {pct} % dos seus registros',
    'db.why.options': 'lista com {n} opções no seu CRM',
    'db.why.standard': 'campo padrão do seu CRM',
    'db.when.today': 'hoje', 'db.when.yesterday': 'ontem',
    'db.when.days': 'há {n} dias', 'db.when.month': 'há um mês', 'db.when.months': 'há {n} meses',
    'db.noteLive': 'O Comando vai consultar ao vivo no seu CRM toda vez que precisar.',
    'db.noteMirror': 'O Comando já pode consultar; os dados antigos se completam em alguns minutos.',
    'db.saveFailed': 'Não foi possível salvar.',
    'db.saveError': 'Não salvou: {msg} Tente de novo.',
    'db.sayOn': '{field}: ativado.',
    'db.sayOff': '{field}: desativado.',
    'db.sayFailed': 'Não foi possível salvar {field}.',
  },
});
